const FETCH_MOVIE_LIST = 'movies/FETCH_MOVIE_LIST'
const FETCH_MOVIE_DETAIL = 'movies/FETCH_MOVIE_DETAIL'
const SET_MOVIE_LIST = 'movies/SET_MOVIE_LIST'
const SET_MOVIE_ITEM = 'movies/SET_MOVIE_ITEM'
const SET_CURRENT_MOVIE = 'movies/SET_CURRENT_MOVIE'
const SET_LIST_TYPE = 'movies/SET_LIST_TYPE'
const SET_TOTAL_PAGES = 'movies/SET_TOTAL_PAGES'

export default {
  FETCH_MOVIE_LIST,
  FETCH_MOVIE_DETAIL,
  SET_MOVIE_LIST,
  SET_MOVIE_ITEM,
  SET_CURRENT_MOVIE,
  SET_LIST_TYPE,
  SET_TOTAL_PAGES
}
